"""add original_data column to surveys

Revision ID: fa292681e507
Revises: 3ca4718379ae
Create Date: 2025-10-29 16:13:54.707114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa292681e507"
down_revision: Union[str, Sequence[str], None] = "3ca4718379ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveys",
        sa.Column(
            "original_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveys", "original_data")
    # ### end Alembic commands ###
