import Link from 'next/link';

/**
 * Says out loud that the numbers above are invented.
 *
 * A dashboard with no data teaches nothing, so a fresh install seeds example
 * calls. Showing invented traffic without labelling it is worse than showing
 * nothing, so this sits above every panel that reads from them and disappears
 * on its own once the example rows are removed.
 */
export default function DemoDataBanner({ count }: { count: number }) {
  if (count === 0) return null;

  return (
    <div className="mb-6 rounded-lg border border-amber-300 bg-amber-50 px-4 py-3">
      <p className="text-sm text-amber-900">
        <span className="font-semibold">{count} example calls.</span> These were generated by{' '}
        <code className="font-mono text-xs bg-amber-100 px-1 py-0.5 rounded">make seed</code> so
        the panels have something to show. They are not real traffic.
      </p>
      <p className="text-xs text-amber-800 mt-1">
        <code className="font-mono bg-amber-100 px-1 py-0.5 rounded">make unseed</code> removes
        them, or{' '}
        <Link href="/chat" className="underline font-medium hover:text-amber-950">
          talk to the agent
        </Link>{' '}
        to record a real one.
      </p>
    </div>
  );
}
